fix: no ckptdir created
Traceback (most recent call last):
  File "/data/hdd1/by/tmp_folder/train.py", line 510, in <module>

  File "/data/hdd1/by/tmp_folder/train.py", line 389, in main
    # if count > 50:
  File "/home/baiyu/miniconda3/envs/torch1.13/lib/python3.10/site-packages/torch/serialization.py", line 422, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "/home/baiyu/miniconda3/envs/torch1.13/lib/python3.10/site-packages/torch/serialization.py", line 309, in _open_zipfile_writer
    return container(name_or_buffer)
  File "/home/baiyu/miniconda3/envs/torch1.13/lib/python3.10/site-packages/torch/serialization.py", line 287, in __init__
    super(_open_zipfile_writer_file, self).__init__(torch._C.PyTorchFileWriter(str(name)))
RuntimeError: Parent directory /data/hdd1/by/tmp_folder/checkpoint/Tuesday_19_December_2023_22h_53m_04s does not exist.